requires 'Mojolicious';
requires 'Mojo::Pg';
requires 'Mojolicious::Plugin::TagHelpers::Pagination';
requires 'Crypt::Passphrase::Argon2';
requires 'Date::Format';
requires 'XML::RSS';
requires 'Text::Markdown';
requires 'HTML::Restrict';
requires 'Roman::Unicode';
