#!/usr/bin/env perl

# PostText v0.1
# Jul 22 2022

use v5.36;
no warnings 'experimental';
use Mojo::File qw{curfile};
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

Mojolicious::Commands->start_app('PostText');
